argo:
  namespace: argocd
  destination:
    name: in-cluster
  sourceRepos:
    - "*"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
